### ISSUE TITLE
Mine sat

### ISSUE THREAD

**Issue by hamiana** [JLChnToZ/mcs2#5]
Hello , please talk about satellite

**Comment by JLChnToZ** [comment]
Sorry, I don't get your point for opening this issue...

**Comment by hamiana** [comment]
You talked about this program, I wanted to know more

**Comment by JLChnToZ** [comment]
Hmmm, what do you want to know more? I think it is enough to explain everything in the README and the site itself.

**Comment by hamiana** [comment]
Thank you, yes it was enough, I am a miner and it was interesting for me

**Comment by hamiana** [comment]
Do you have information about beneath the surface and remote sensing?

**Comment by JLChnToZ** [comment]
Not sure what do you mean. Basically this site is just an automatic server pinger which regularly pings and list them out like a regular game client.

**Comment by hamiana** [comment]
I almost found out about that site, do you have any information about remote sensing that is helpful?

**Comment by JLChnToZ** [comment]
Pardon, what "remote sensing" means? Is that means you want to sniff a server from nowhere or just keep tracking if the server is online?

**Comment by hamiana** [comment]
satellite remote sensing And transfer it to the smartphone

**Comment by JLChnToZ** [comment]
Two parts:
1. Use the Minecraft Protocol as same as the game client to get information from the servers.
  you may see how to do it on [wiki.vg](https://wiki.vg/Server_List_Ping) and [pingger.js](https://github.com/JLChnToZ/mcs2/blob/master/lib/pingger.js)
2. Use websocket to send update information to browsers
  for example on this site, we use [socket.io](https://socket.io/) to do it.

**Comment by JLChnToZ** [comment]
I think before you asking, you should learn how to write a Node.js server that host a dynamic website first. Once you learnt how to do it, it is not so difficult to see how this site works. This is just a mini project and does not involve complex stuffs in it.

**Comment by hamiana** [comment]
Yes, you're right, I don't know anything about this, I just wanted to know if it is possible to transfer satellite data and remote sensing to a smartphone.

**Comment by JLChnToZ** [comment]
Why not? There are plenty of libraries and frameworks that you can use to create something like this on a smartphone. I cannot teach you because I am not an expert on creating mobile app either. The only thing I can tell is you can do it. Good luck to find your way.

**Comment by hamiana** [comment]
Thank you very much for your explanation. Dear, I have recently entered this field. Can you please introduce the website or someone who specializes in this work?

**Comment by JLChnToZ** [comment]
Kinda hard to tell, I'm not familiar with this field. But I will use Google when I needed.

**Comment by hamiana** [comment]
Thank you, I will definitely search on Google, but some content on Google pages has been deleted

**Comment by hamiana** [comment]
Does Google Earth have a program that can detect underground cavities? thank you

**Comment by JLChnToZ** [comment]
You are already asking something out of my knowledge scope, should we end this topic?

Also I think you misunderstand what this site is about, although there has a word "satellite" in the title, this is not related to the real satellites that flying on the space. This is just a third-party service that works with multiplayer servers for Minecraft, which is a sandbox simulation game.

This is also the reason why I don't know what you talking about, because I am not and I was not a developer of clients/services integrated with real satellites.

**Comment by hamiana** [comment]
thank you , please forgive me for the successive questions
